<?php

namespace AppBundle\Repository;

/**
 * RepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryRepository extends \Doctrine\ORM\EntityRepository
{
}
